Libbna/CUSTOM-CMS

- composer.json
- composer.lock
- custom_cms.sql
Added sql file containing database to work on.
> Added sql file

- .gitignore
- .htaccess
- index.php
- routes/route.php
* Redirected all incoming requests/routes to route.php file, where they will be forwarded to their respective controllers.
> #1: Added routing to the site

- index.php
- routes/route.php
- templates/home.html.twig
- twigtemplate.php
- views/templates/home.html.twig
* The twigtemplate.php file will serve as the initialising file for twig.
* All the view template files (or twig) files will be stored under "views/templates" directory.
> Added twig template engine which will be the View part of the MVC

- controllers/Home.php
- routes/route.php
* Pointed home route to home controller containing dummy data.
* The controller function then renders the respective template file
> #1: Added the controller function to the home route

- controllers/Contact.php
- controllers/Controller.php
- controllers/Home.php
- models/Models.php
- routes/route.php
- views/templates/contact.html.twig
- views/templates/home.html.twig
* Solved the issues in model.php
* fetch the users from database and displaying on the browser using MVC model
> Solved the issues and created model function.

- assets/css/style.css
- models/Models.php
- views/templates/contact.html.twig
- views/templates/home.html.twig
- views/templates/layout.html.twig
* Added bootstrap to the site.
* Created a custom css file as well.
* Created a layout for twig template.
* styled the contact page of the site.
> #17: Started withe the theming of the site

- assets/css/style.css
- views/templates/home.html.twig
* Added insert form to homepage of the site.
> Added form to the home page

- controllers/Contact.php
- models/Models.php
- routes/route.php
- views/templates/home.html.twig
* Inserted User Details in the database
> #24: Inserted User details in the database

- composer.json
- composer.lock
- routes/route.php
* Installed symfony-routing component and rest of the dependencies required.
* Also added styling to contact.html.twig template.
> Shifted the symfony-routing code to route.php filr

- routes/route.php
* Removed commented/unnecessary code from route.php
> #30: Removed all the commented/unecessary code from route.php

- route.php
- src/Controllers/CustomBlock.php
- views/templates/blockDisplay.html.twig
- views/templates/layout.html.twig
* Added a controller method `customBlockInfo()` which will display the custom blocks.
> #43: Added a controller which will display the custom block

- route.php
- src/Controllers/CustomBlock.php
- views/templates/block.html.twig
- views/templates/layout.html.twig
* Added an insert-block-details controller function to the CustomBlock controller.
* This function deals with the insertion of block details in the database.
> #43: Custom block controller

- custom_cms.sql
- route.php
- src/Controllers/CustomBlock.php
- src/Models/Database.php
- views/templates/block.html.twig
- views/templates/blockDisplay.html.twig
- views/templates/layout.html.twig
* Inserted the block details in the database successfully.
* Fetched and displayed all the custom-blocks from the database.
* Updated the layout template and route.php file
* Created a nav-link which points to the template where the custom-block list is getting displayed.
> #43:  custom-block controller function.

- route.php
- src/Controllers/CustomBlock.php
- src/Models/Database.php
- views/templates/home.html.twig
* The insert block operation is now working.
> #43: Fixed the insert contact bug

- composer.json
- composer.lock
- route.php
- src/Controllers/Db_auth.php
- src/Models/Database.php
- src/User/DatabaseUserProvider.php
- src/User/User.php
* Added user authentication to the CMS.
* Used Symfony Security Component.
> #63: Added User Authentication to Cms.

- route.php
- src/Controllers/Db_auth.php
- views/templates/home.html.twig
- views/templates/loginForm.html.twig
- views/templates/registerForm.html.twig
* Added dynamic info to the CMS.
> #67: Fixed the issue, made the user info and other details dynamic

- .gitignore
- custom_cms.sql
- route.php
- src/Controllers/Contact.php
- src/Controllers/CustomBlock.php
- src/Controllers/Db_auth.php
- src/Controllers/Home.php
- src/User/DatabaseUserProvider.php
- src/User/User.php
- views/templates/home.html.twig
* Restricted user from some pages. (Example - login, register).
* Added logout.
* Code cleanup.
> #73 : Logout feature and code cleanup.

- custom_cms.sql
- route.php
- src/Controllers/Article.php
- src/Controllers/Db_auth.php
- src/Models/ArticleModel.php
- src/Models/Database.php
- src/User/DatabaseUserProvider.php
- src/User/User.php
- views/templates/articleForm.html.twig
* Added article content type.
* Authenticated user can now add the articles and blogs to the CMS.
* Restricted the article form page to authenticated users only.
> #78: Added article content type.

- views/templates/articleForm.html.twig
- views/templates/block.html.twig
- views/templates/home.html.twig
- views/templates/layout.html.twig
- views/templates/loginForm.html.twig
- views/templates/registerForm.html.twig
* The routes issue in forms has been resolved.
* Added HTML base tag in layout template.
> #81: Resolved the routes issue using base tag

- views/templates/articleForm.html.twig
- views/templates/contactForm.html.twig
- views/templates/home.html.twig
- views/templates/layout.html.twig
* Added image and category fields to article content type.
* Changes in home template and layout template.
> #85: Add fields to article content type.

- src/Controllers/Article.php
- src/Models/ArticleModel.php
- views/templates/articleForm.html.twig
- views/templates/layout.html.twig
Added 2 extra fields in articles' table, category and image. 
Category data is also getting stored in DB along with articles' title and body.
> #85 added category field with insertion query

- .htaccess
- load_routes.php
- routes.yaml
created `routes.yml `file.
added all the routes with controller in yml file.
created `load_routes.php` file to load all the routes from the `routes.yml `file.
> #83: declared routes in yaml file.
